// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockManagerCore.Data;

namespace StockManagerCore.Migrations
{
    [DbContext(typeof(StockDBContext))]
    [Migration("20201014185315_InitialCreation")]
    partial class InitialCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StockManagerCore.Models.InputProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IQty")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("StockId")
                        .HasColumnType("int");

                    b.Property<int?>("StockId1")
                        .HasColumnType("int");

                    b.Property<double>("UnValue")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.HasIndex("StockId");

                    b.HasIndex("StockId1");

                    b.ToTable("InputProducts");
                });

            modelBuilder.Entity("StockManagerCore.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Group")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("StockManagerCore.Models.SoldProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SQty")
                        .HasColumnType("int");

                    b.Property<double>("SUnValue")
                        .HasColumnType("float");

                    b.Property<int?>("StockId")
                        .HasColumnType("int");

                    b.Property<int?>("StockId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.HasIndex("StockId");

                    b.HasIndex("StockId1");

                    b.ToTable("SoldProducts");
                });

            modelBuilder.Entity("StockManagerCore.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("StockManagerCore.Models.InputProduct", b =>
                {
                    b.HasOne("StockManagerCore.Models.Product", "ProductNav")
                        .WithOne("InputProduct")
                        .HasForeignKey("StockManagerCore.Models.InputProduct", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockManagerCore.Models.Stock", null)
                        .WithMany("InputProducts")
                        .HasForeignKey("StockId");

                    b.HasOne("StockManagerCore.Models.Stock", null)
                        .WithMany("ProductsInputs")
                        .HasForeignKey("StockId1");
                });

            modelBuilder.Entity("StockManagerCore.Models.SoldProduct", b =>
                {
                    b.HasOne("StockManagerCore.Models.Product", "Product")
                        .WithOne("SoldProduct")
                        .HasForeignKey("StockManagerCore.Models.SoldProduct", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockManagerCore.Models.Stock", null)
                        .WithMany("ProductsSales")
                        .HasForeignKey("StockId");

                    b.HasOne("StockManagerCore.Models.Stock", null)
                        .WithMany("SoldProducts")
                        .HasForeignKey("StockId1");
                });
#pragma warning restore 612, 618
        }
    }
}
