// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockManagerCore.Data;

namespace StockManagerCore.Migrations
{
    [DbContext(typeof(StockDBContext))]
    [Migration("20201026202955_v6ContextSeed")]
    partial class v6ContextSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StockManagerCore.Models.InputProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DhEmi")
                        .HasColumnType("datetime2");

                    b.Property<string>("NItem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("QCom")
                        .HasColumnType("int");

                    b.Property<string>("UCom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("VTotTrib")
                        .HasColumnType("float");

                    b.Property<double>("VUnCom")
                        .HasColumnType("float");

                    b.Property<double>("VUnTrib")
                        .HasColumnType("float");

                    b.Property<double>("Vtotal")
                        .HasColumnType("float");

                    b.Property<string>("XProd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("InputProducts");
                });

            modelBuilder.Entity("StockManagerCore.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Group")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Group = "ANEL"
                        },
                        new
                        {
                            Id = 2,
                            Group = "ARGOLA"
                        },
                        new
                        {
                            Id = 3,
                            Group = "BRACELETE"
                        },
                        new
                        {
                            Id = 4,
                            Group = "BRINCO"
                        },
                        new
                        {
                            Id = 5,
                            Group = "CHOCER"
                        },
                        new
                        {
                            Id = 6,
                            Group = "COLAR"
                        },
                        new
                        {
                            Id = 7,
                            Group = "CORRENTE"
                        },
                        new
                        {
                            Id = 8,
                            Group = "PINGENTE"
                        },
                        new
                        {
                            Id = 9,
                            Group = "PULSEIRA"
                        },
                        new
                        {
                            Id = 10,
                            Group = "TORNOZELEIRA"
                        },
                        new
                        {
                            Id = 11,
                            Group = "PEAÇAS"
                        },
                        new
                        {
                            Id = 12,
                            Group = "VARIADOS"
                        },
                        new
                        {
                            Id = 13,
                            Group = "BROCHE"
                        });
                });

            modelBuilder.Entity("StockManagerCore.Models.SoldProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DhEmi")
                        .HasColumnType("datetime2");

                    b.Property<string>("NItem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("QCom")
                        .HasColumnType("int");

                    b.Property<double>("VUnCom")
                        .HasColumnType("float");

                    b.Property<double>("Vtotal")
                        .HasColumnType("float");

                    b.Property<string>("XProd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("SoldProducts");
                });

            modelBuilder.Entity("StockManagerCore.Models.InputProduct", b =>
                {
                    b.HasOne("StockManagerCore.Models.Product", "Product")
                        .WithMany("InputProduct")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("StockManagerCore.Models.SoldProduct", b =>
                {
                    b.HasOne("StockManagerCore.Models.Product", "Product")
                        .WithMany("SoldProduct")
                        .HasForeignKey("ProductId");
                });
#pragma warning restore 612, 618
        }
    }
}
